service: import-service

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

  environment:
    SQS_URL: !Ref SQSQueue

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::${self:custom.bucketName}'
    - Effect: "Allow"
      Action: "s3:*"
      Resource:
        - 'arn:aws:s3:::${self:custom.bucketName}/*'
    - Effect: 'Allow'
      Action: 'sqs:*'
      Resource:
        - Fn::GetAtt: [SQSQueue, Arn]

custom:
  bucketName: env:BUCKET_NAME
  webpack:
    webpackConfig: webpack.config.cjs
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  importProductsFile:
    handler: handlers/importProductsFile.default
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            arn: env:TOKEN_AUTHORIZER_ARN
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
  importFileParser:
    handler: handlers/importFileParser.default
    events:
      - s3:
          bucket: ${env:S3_NAME}
          event: 's3:ObjectCreated:*'
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
