service: authorization-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

functions:
  basicAuthorizer:
    handler: handlers/basicAuthorizer.default
    events:
      - http:
          path: /token
          method: get

custom:
  webpack:
    webpackConfig: webpack.config.cjs
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
